import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Harshit-portfolio",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-dark bg-[rgb(8,50,78)] text-info font-mono">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
